function [cf, pp, resout] = plotGRINTracingResults(savepath)
% PLOTGRINTRACINGRESULTS  Load and display GRIN lens tracing results saved
%   by annotateGRINLens in a LightSuite folder.
%
%   [CF, PP, RESOUT] = plotGRINTracingResults(SAVEPATH)
%
%   Searches SAVEPATH for every  grin_fiber<N>_atlas.mat  file produced by
%   annotateGRINLens (one per annotated fiber), loads them in ascending
%   fiber-number order, then:
%
%   1. Calls plotGRINAtlasImages to show:
%       • a 3-D brain-grid plot with colour-coded fiber cylinders, and
%       • one row of circular parcellation-region panels per fiber across
%         all recorded depths.
%
%   2. If  SAVEPATH/volume_registered/  exists (generated by
%      generateRegisteredSliceVolume), also calls extractGRINIntensitySlices
%      and plotGRINIntensityImages to produce a companion figure showing the
%      actual fluorescence intensity cross-sections for every channel at the
%      same depths.
%
%   The Allen CCF atlas resources (annotation_10.nii.gz and
%   parcellation_to_parcellation_term_membership.csv) must be on the
%   MATLAB path, exactly as required by annotateGRINLens.
%
%   Usage
%   -----
%       plotGRINTracingResults(savepath)
%       [cf, pp, resout] = plotGRINTracingResults(savepath)
%
%   Inputs
%   ------
%   savepath  – LightSuite output folder in which annotateGRINLens was run.
%               Must contain at least one  grin_fiber*_atlas.mat  file.
%
%   Outputs (optional)
%   ------------------
%   cf     – handle to the atlas-annotation figure (plotGRINAtlasImages).
%   pp     – panel object returned by plotGRINAtlasImages.
%   resout – struct with fields:
%               .all_results        – loaded fiber atlas structs
%               .intensity_results  – per-fiber intensity structs (empty if
%                                     volume_registered/ is absent)
%               .channames          – channel name strings (empty if above)
%               .cf_atlas           – atlas figure handle
%               .cf_intensity       – intensity figure handle ([] if absent)
%
%   Example
%   -------
%       plotGRINTracingResults('/data/mouse01/lightsuite_output');

    %----------------------------------------------------------------------
    % 1. Find saved per-fiber result files
    %----------------------------------------------------------------------
    pattern   = fullfile(savepath, 'grin_fiber*_atlas.mat');
    flist     = dir(pattern);

    if isempty(flist)
        error('plotGRINTracingResults: no grin_fiber*_atlas.mat files found in:\n  %s', savepath);
    end

    % Sort by the embedded fiber number (e.g. grin_fiber3_atlas.mat → 3)
    fiber_nums = zeros(1, numel(flist));
    for k = 1:numel(flist)
        tok = regexp(flist(k).name, 'grin_fiber(\d+)_atlas', 'tokens', 'once');
        if ~isempty(tok)
            fiber_nums(k) = str2double(tok{1});
        end
    end
    [~, sort_idx] = sort(fiber_nums);
    flist = flist(sort_idx);

    fprintf('plotGRINTracingResults: found %d fiber result file(s) in\n  %s\n', ...
        numel(flist), savepath);

    %----------------------------------------------------------------------
    % 2. Load per-fiber structs
    %----------------------------------------------------------------------
    all_results = cell(1, numel(flist));
    for k = 1:numel(flist)
        fpath = fullfile(flist(k).folder, flist(k).name);
        fprintf('  Loading %s ...\n', flist(k).name);
        s = load(fpath);

        % Validate that the required fields are present
        required = {'center_vox', 'normal_vox', 'radius_vox', ...
                    'atlas_pts', 'depths_um', 'slices_av', 'rvec_arr'};
        missing = required(~isfield(s, required));
        if ~isempty(missing)
            error('plotGRINTracingResults: file %s is missing field(s): %s', ...
                flist(k).name, strjoin(missing, ', '));
        end

        all_results{k} = s;
    end

    %----------------------------------------------------------------------
    % 3. Load Allen CCF atlas resources (annotation volume + parcellation)
    %----------------------------------------------------------------------
    allen_atlas_path = fileparts(which('annotation_10.nii.gz'));
    if isempty(allen_atlas_path)
        error('plotGRINTracingResults: annotation_10.nii.gz not found on the MATLAB path.');
    end

    parcel_path = fileparts(which('parcellation_to_parcellation_term_membership.csv'));
    if isempty(parcel_path)
        error('plotGRINTracingResults: parcellation_to_parcellation_term_membership.csv not found on the MATLAB path.');
    end

    fprintf('Loading parcellation table ...\n');
    parcelinfo = readtable(fullfile(parcel_path, 'parcellation_to_parcellation_term_membership.csv'));

    substridx   = strcmp(parcelinfo.parcellation_term_set_name, 'substructure');
    [areaidx, ib] = unique(parcelinfo.parcellation_index(substridx));
    namessub    = parcelinfo.parcellation_term_acronym(substridx);
    namessub    = namessub(ib);
    colorsub    = [parcelinfo.red(substridx), ...
                   parcelinfo.green(substridx), ...
                   parcelinfo.blue(substridx)];
    colorsub    = colorsub(ib, :);

    %----------------------------------------------------------------------
    % 4. Atlas annotation figure
    %----------------------------------------------------------------------
    fprintf('Plotting atlas annotation figure (%d fiber(s)) ...\n', numel(all_results));
    [cf, pp, resout] = plotGRINAtlasImages(all_results, areaidx, namessub, colorsub);

    if ~isempty(cf)
        cf.Name = sprintf('GRIN Atlas Regions – %s', savepath);
    end

    %----------------------------------------------------------------------
    % 5. Intensity figure (only when volume_registered/ is present)
    %----------------------------------------------------------------------
    cf_intensity       = [];
    intensity_results  = {};
    channames_int      = {};

    if exist(fullfile(savepath, 'volume_registered'), 'dir')
        fprintf('Found volume_registered/ – extracting intensity profiles ...\n');
        try
            [intensity_results, channames_int] = ...
                extractGRINIntensitySlices(savepath, all_results);
            [cf_intensity, ~] = plotGRINIntensityImages( ...
                all_results, intensity_results, channames_int);
            if ~isempty(cf_intensity)
                cf_intensity.Name = sprintf('GRIN Intensity Profiles – %s', savepath);
            end
        catch ME
            warning('plotGRINTracingResults: intensity extraction failed:\n  %s', ME.message);
        end
    else
        fprintf('(volume_registered/ not found – skipping intensity figure)\n');
    end

    %----------------------------------------------------------------------
    % 6. Pack optional output struct
    %----------------------------------------------------------------------
    if nargout >= 3
        resout.all_results       = all_results;
        resout.intensity_results = intensity_results;
        resout.channames         = channames_int;
        resout.cf_atlas          = cf;
        resout.cf_intensity      = cf_intensity;
    end
end
